const routes = require('express').Router();
const userControlerRoutes = require('./User');
const questionController = require("./question");
const templateCtrl = require("./template");
const chatCtrl = require("./chat");
routes.use('/', userControlerRoutes);
routes.use('/question', questionController);
routes.use('/template', templateCtrl);
routes.use('/chat', chatCtrl);
module.exports = routes;